# Generated by Django 5.0.2 on 2024-02-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizntree_dashboard', '0002_rename_todo_dashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('stock_status', models.CharField(max_length=20)),
                ('available_stock', models.IntegerField()),
                ('tags', models.ManyToManyField(to='kaizntree_dashboard.tag')),
            ],
        ),
        migrations.DeleteModel(
            name='Dashboard',
        ),
    ]
